version: "3.9"

name: sigesp

services:
  web:
    container_name: sigesp_web
    build:
      context: ../
      dockerfile: ./deployments/web/Dockerfile
    env_file: "./web/.env.dev"
    ports:
      - "8080:8080"
    depends_on:
      - api
  api:
    container_name: sigesp_api
    build:
      context: ../
      dockerfile: ./deployments/api/Dockerfile
    env_file: "./api/.env.dev"
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    container_name: sigesp_db
    image: postgres:15.3-alpine
    env_file: "./postgres/.env.dev"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/scripts/:/docker-entrypoint-initdb.d/:z
  db_admin:
    container_name: sigesp_db_admin
    image: dpage/pgadmin4:latest
    env_file: "./pgadmin/.env.dev"
    ports:
      - "9090:80"
    logging:
      driver: none
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json:z
    depends_on:
      - db

volumes:
  postgres_data: