version: "3.9"

name: vega

services:
  web:
    container_name: vega_web
    build:
      context: ../
      dockerfile: ./deployments/web/Dockerfile
    env_file: "./web/.env.dev"
    ports:
      - "8080:8080"
    depends_on:
      - api
  api:
    container_name: vega_api
    build:
      context: ../
      dockerfile: ./deployments/api/Dockerfile
    env_file: "./api/.env.dev"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  postgres:
    container_name: vega_postgres
    image: postgres:15.3-alpine
    env_file: "./postgres/.env.dev"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/scripts/:/docker-entrypoint-initdb.d/:z
  pgadmin:
    container_name: vega_pgadmin
    image: dpage/pgadmin4:latest
    env_file: "./pgadmin/.env.dev"
    ports:
      - "9090:80"
    logging:
      driver: none
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json:z
    depends_on:
      - postgres
  kratos-migrate:
    image: oryd/kratos:v0.13.0
    environment:
      - DSN=postgres://postgres:secret@postgres:5432/obgov?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - ./kratos:/etc/config/kratos:z
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
  kratos:
    container_name: vega_kratos
    image: oryd/kratos:v0.13.0
    environment:
      - DSN=postgres://postgres:secret@postgres:5432/obgov?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
    volumes:
      - ./kratos:/etc/config/kratos:z
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    depends_on:
      - kratos-migrate
      - postgres
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v0.13.0
    ports:
      - "4455:4455"
    environment:
      - PORT=4455
      - SECURITY_MODE=
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_BROWSER_URL=http://127.0.0.1:4433/

volumes:
  postgres_data: